[package]
name = "xelu_free_controller_key_prompts"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
fs_extra = "1.3.0"
tokenize_dir = {version = "0.1.0", optional = true}

[features]
default = []
use_tokenize_dir = ["tokenize_dir"]